### ISSUE TITLE
Double Actor Payload

### ISSUE THREAD

**Issue by etoilebleu** [enorfelt/node-red-contrib-pid-autotune#1]
Using NodeRed v1.06 on RPi4, I am seeing Output 2 (to the Actor) sending two messages at a time.
![image](https://user-images.githubusercontent.com/23141061/104386489-eece8080-54fa-11eb-8793-0398b4627c19.png)

This happens when the output step% is not 100 (ex. set to 10 or 50).

Seems to work otherwise (ex. output step set to 100).

**Comment by enorfelt** [comment]
> Using NodeRed v1.06 on RPi4, I am seeing Output 2 (to the Actor) sending two messages at a time.
> ![image](https://user-images.githubusercontent.com/23141061/104386489-eece8080-54fa-11eb-8793-0398b4627c19.png)
> 
> This happens when the output step% is not 100 (ex. set to 10 or 50).
> 
> Seems to work otherwise (ex. output step set to 100).

Thx for your feedback! Will look into it!

**Comment by b0g3r** [comment]
@enorfelt Thank you for such a great extension for node-red, I really appreciate it. Maybe you have some workaround for avoiding doubling in systems with smaller than 100 step?

**Comment by enorfelt** [comment]
> @enorfelt Thank you for such a great extension for node-red, I really appreciate it. Maybe you have some workaround for avoiding doubling in systems with smaller than 100 step?

No unfortunately not at the moment. I think I made some mistakes with async operations. I'm working on a solution. Sorry for any inconveniences.
