### ISSUE TITLE
Unable to stop Auto Tune, and crashing flow

### ISSUE THREAD

**Issue by stamandster** [enorfelt/node-red-contrib-pid-autotune#5]
Sending msg.payload of "stop" does not stop the auto tune. Also, if sending anything before the auto tune starts crashes the flow. Any help would be appreciated. It would also be great to be able to send setpoint temp instead of having to put it directly into the node configuration.

**Comment by dalethomas81** [comment]
I believe you should be sending msg.cmd = stop

Also, can you add some details about your environment? What node-red version and what version of node-red-contrib-pid-autotune?

**Comment by stamandster** [comment]
For testing, I'm injecting a number into msg.payload (either with or without a topic doesn't work; msg.payload value is set to type: number) to start the process, then injecting msg.cmd value of "stop".

![image](https://user-images.githubusercontent.com/35270181/150552325-594dcf6b-5e2f-49c2-99fa-aae260f4a204.png)

Both crash node-red

![image](https://user-images.githubusercontent.com/35270181/150552533-62076326-f5a8-47ab-96bc-4ddf348939c4.png)

When I use temperature from a GPIO pin the process starts, but, I'm unable to stop it once it begins since it kills node-red with the above error.

![image](https://user-images.githubusercontent.com/35270181/150552832-edf42631-574a-4ccc-85e4-b8a9e1f968f8.png)

Node-RED version: v2.1.5
Node.js  version: v16.13.2

**Comment by dalethomas81** [comment]
Ok yes, I came across this because my topic was not set to the same as what is configured in the auto-tune node. 

Away from my project now but I can show you why later. It is a bug in the reject where it captures temperature. 

I will send you my test code later but for now check your topic value.

**Comment by dalethomas81** [comment]
Also, before I forget - you mentioned wanting to be able to send the setpoint. You can do that now. In the configuration, change your setpoint type to msg.setpoint and then you can send the value.

**Comment by stamandster** [comment]
Wow thanks! Does that need to happen before the process starts? Or can it be adjusted during also? And it needs to be the same topic as the temperature topic?

**Comment by dalethomas81** [comment]
This is the code if you want to read more but basically, as soon as there is a input seen at the node, it will check to see if it is currently running an autotune. If it is not, it will "getSetpoint". What that does is looks to see if you have it configured to be dynamically sent with the input or just hardcoded in the node.

It does not care about the topic. However, the "getCurrentTemp" function does. That is why you have an issue. If it does not see the topic being the same it rejects the promise. But there is no try-catch to handle that so it crashes. You can see that in this line [here](https://github.com/enorfelt/node-red-contrib-pid-autotune/blob/03cdd29740a86f2f140a7b772940e436504bbf58/pid-autotune.js#L73).

https://github.com/enorfelt/node-red-contrib-pid-autotune/blob/main/pid-autotune.js

**Comment by stamandster** [comment]
OK thank you. Just trying to figure out how to add this to the flow and get it to work properly. I'm a node-red newb!

**Comment by enorfelt** [comment]
Thank you for your greate discussion and input! 
Regarding the try/catch. My thought was to use the try/catch nodes. As I understand the node-red docs says it should be handled like that.

Is there any other issues now open? Let me know if you have any other suggestions. If there is a bug it should be solved. Thank you!

**Comment by dalethomas81** [comment]
Ha! I think we are all node-red newbs :) But yes, I just started using this node yesterday. I will eventually post my working example for @stamandster and will create a PR for the bug we found.

**Comment by dalethomas81** [comment]
And also thank you so much for bringing this to node-red. My application is a kiln and this will work very nicely.

**Comment by enorfelt** [comment]
@dalethomas81 very cool (mostly hot? 😂)!
Yes please create a PR and I'll have a look. Been a while since I was inte the space of node-red. I'm glad this is used and get feedback on it.

**Comment by stamandster** [comment]
Thanks All! This is wonderful! There's also a misspelling for "Stoped", should be "Stopped".

**Comment by enorfelt** [comment]
I could close this right?

**Comment by stamandster** [comment]
Yessir
